[build]
  command = "yarn build" # the command you run to build this file 
  publish = "build" # create-react-app builds to this folder, Netlify should serve all these files statically
  
[build.environment]
  YARN_VERSION = "1.17.3"
  NODE_ENV = "production"
